### ISSUE TITLE
Downgrade QoS 2 subscribers to QoS 1

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-mqtt#21]
Currently we fail with an error. MQTT 3.1 allows for downgrades and has a non-existent error notifications story, so a much better idea would be to downgrade QoS 2 requests to QoS 1.

**Comment by michaelklishin** [comment]
This is technically fixed in master but we haven't updated the docs yet => re-opening.

**Comment by michaelklishin** [comment]
Docs updated in https://github.com/rabbitmq/rabbitmq-website/pull/147. Thank you, @hairyhum.

**Comment by grassy-noel** [comment]
Does the QOS2->QOS1 downgrade still work as per the Web-site docs?
My experience with 3.6.14 on Windows and 3.70 on Linux is that the connection drops.

Windows - Mosquitto


"C:\Program Files (x86)\mosquitto\mosquitto_pub.exe" -h localhost -p 1883  -t home.garden.fountain -m "test message" -q 2
Error: The connection was lost.

MQTT-fx using Paho works with QOS0 and QOS1

2017-12-14 05:29:42,987  INFO --- MqttFX ClientModel             : attempt to add PublishTopic
2017-12-14 05:29:42,987  INFO --- MqttFX ClientModel             : addPublishTopic : home.garden.fountain
2017-12-14 05:29:42,988  INFO --- MqttFX ClientModel             : sucessfully published message Test @ QOS0 to topic home.garden.fountain (QoS 0, Retained false)
2017-12-14 05:29:52,956  INFO --- PublishController              : publish
2017-12-14 05:29:52,957  INFO --- MqttFX ClientModel             : attempt to add PublishTopic
2017-12-14 05:29:52,958  INFO --- MqttFX ClientModel             : sucessfully published message Test @ QOS0 to topic home.garden.fountain (QoS 0, Retained false)
2017-12-14 05:30:06,316  INFO --- PublishController              : publish
2017-12-14 05:30:06,320  INFO --- MqttFX ClientModel             : attempt to add PublishTopic
2017-12-14 05:30:06,321  INFO --- MqttFX ClientModel             : sucessfully published message Test @ QOS1 to topic home.garden.fountain (QoS 1, Retained false)
2017-12-14 05:30:07,066  INFO --- PublishController              : publish
2017-12-14 05:30:07,068  INFO --- MqttFX ClientModel             : attempt to add PublishTopic
2017-12-14 05:30:07,068  INFO --- MqttFX ClientModel             : sucessfully published message Test @ QOS1 to topic home.garden.fountain (QoS 1, Retained false)
2017-12-14 05:30:14,853  INFO --- PublishController              : publish
2017-12-14 05:30:14,857  INFO --- MqttFX ClientModel             : Broker connection lost: Retrying...
2017-12-14 05:30:14,857 ERROR --- MqttFX ClientModel             : Error publishing to topic: home.garden.fountain
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(Unknown Source) ~[?:1.8.0_131]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	... 1 more
2017-12-14 05:30:16,063  INFO --- PublishController              : publish
2017-12-14 05:30:16,066 ERROR --- MqttFX ClientModel             : Error publishing to topic: home.garden.fountain
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(Unknown Source) ~[?:1.8.0_131]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	... 1 more
2017-12-14 05:30:16,067  INFO --- MqttFX ClientModel             : Broker connection lost: Retrying...
2017-12-14 05:30:16,352  INFO --- PublishController              : publish
2017-12-14 05:30:16,352 ERROR --- MqttFX ClientModel             : Error publishing to topic: home.garden.fountain
org.eclipse.paho.client.mqttv3.MqttException: Client is not connected
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]

**Comment by michaelklishin** [comment]
@grassy-noel our team does not use Github issues for investigations. Please start a rabbitmq-users thread, provide a list of steps to reproduce and server logs.
